//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Test {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("searcher", Namespace="http://rest.immobilienscout24.de/schema/search/searcher/1.0", IsNullable=false)]
    public partial class User {
        
        private ContactDetails contactDetailsField;
        
        private string passwordField;
        
        private long sharedShortlistGroupIdField;
        
        private bool sharedShortlistGroupIdFieldSpecified;
        
        private string idField;
        
        private long peidField;
        
        private bool peidFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContactDetails contactDetails {
            get {
                return this.contactDetailsField;
            }
            set {
                this.contactDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sharedShortlistGroupId {
            get {
                return this.sharedShortlistGroupIdField;
            }
            set {
                this.sharedShortlistGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sharedShortlistGroupIdSpecified {
            get {
                return this.sharedShortlistGroupIdFieldSpecified;
            }
            set {
                this.sharedShortlistGroupIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long peid {
            get {
                return this.peidField;
            }
            set {
                this.peidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool peidSpecified {
            get {
                return this.peidFieldSpecified;
            }
            set {
                this.peidFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExposeContactDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealtorContactDetails))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class ContactDetails : BaseContactDetails {
        
        private string officeHoursField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string officeHours {
            get {
                return this.officeHoursField;
            }
            set {
                this.officeHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExposeContactDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealtorContactDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MasterDataContactDetailsType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class BaseContactDetails {
        
        private string emailField;
        
        private SalutationType salutationField;
        
        private bool salutationFieldSpecified;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string faxNumberCountryCodeField;
        
        private string faxNumberAreaCodeField;
        
        private string faxNumberSubscriberField;
        
        private string faxNumberField;
        
        private string phoneNumberCountryCodeField;
        
        private string phoneNumberAreaCodeField;
        
        private string phoneNumberSubscriberField;
        
        private string phoneNumberField;
        
        private string cellPhoneNumberCountryCodeField;
        
        private string cellPhoneNumberAreaCodeField;
        
        private string cellPhoneNumberSubscriberField;
        
        private string cellPhoneNumberField;
        
        private Address addressField;
        
        private CountryCode countryCodeField;
        
        private bool countryCodeFieldSpecified;
        
        private string titleField;
        
        private string additionNameField;
        
        private string companyField;
        
        private string homepageUrlField;
        
        private string portraitUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SalutationType salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salutationSpecified {
            get {
                return this.salutationFieldSpecified;
            }
            set {
                this.salutationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string faxNumberCountryCode {
            get {
                return this.faxNumberCountryCodeField;
            }
            set {
                this.faxNumberCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string faxNumberAreaCode {
            get {
                return this.faxNumberAreaCodeField;
            }
            set {
                this.faxNumberAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string faxNumberSubscriber {
            get {
                return this.faxNumberSubscriberField;
            }
            set {
                this.faxNumberSubscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string faxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNumberCountryCode {
            get {
                return this.phoneNumberCountryCodeField;
            }
            set {
                this.phoneNumberCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNumberAreaCode {
            get {
                return this.phoneNumberAreaCodeField;
            }
            set {
                this.phoneNumberAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNumberSubscriber {
            get {
                return this.phoneNumberSubscriberField;
            }
            set {
                this.phoneNumberSubscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cellPhoneNumberCountryCode {
            get {
                return this.cellPhoneNumberCountryCodeField;
            }
            set {
                this.cellPhoneNumberCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cellPhoneNumberAreaCode {
            get {
                return this.cellPhoneNumberAreaCodeField;
            }
            set {
                this.cellPhoneNumberAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cellPhoneNumberSubscriber {
            get {
                return this.cellPhoneNumberSubscriberField;
            }
            set {
                this.cellPhoneNumberSubscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CountryCode countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countryCodeSpecified {
            get {
                return this.countryCodeFieldSpecified;
            }
            set {
                this.countryCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string additionName {
            get {
                return this.additionNameField;
            }
            set {
                this.additionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string homepageUrl {
            get {
                return this.homepageUrlField;
            }
            set {
                this.homepageUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string portraitUrl {
            get {
                return this.portraitUrlField;
            }
            set {
                this.portraitUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public enum SalutationType {
        
        /// <remarks/>
        FEMALE,
        
        /// <remarks/>
        MALE,
        
        /// <remarks/>
        COMPANY,
        
        /// <remarks/>
        NO_SALUTATION,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wgs84Address))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Address {
        
        private string streetField;
        
        private string houseNumberField;
        
        private string postcodeField;
        
        private string cityField;
        
        private CountryRegion internationalCountryRegionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string houseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CountryRegion internationalCountryRegion {
            get {
                return this.internationalCountryRegionField;
            }
            set {
                this.internationalCountryRegionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class CountryRegion {
        
        private CountryCode countryField;
        
        private string regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CountryCode country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public enum CountryCode {
        
        /// <remarks/>
        ABW,
        
        /// <remarks/>
        AFG,
        
        /// <remarks/>
        AGO,
        
        /// <remarks/>
        AIA,
        
        /// <remarks/>
        ALB,
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        ANT,
        
        /// <remarks/>
        ARE,
        
        /// <remarks/>
        ARG,
        
        /// <remarks/>
        ARM,
        
        /// <remarks/>
        ASM,
        
        /// <remarks/>
        ATA,
        
        /// <remarks/>
        ATG,
        
        /// <remarks/>
        AUS,
        
        /// <remarks/>
        AUT,
        
        /// <remarks/>
        AZE,
        
        /// <remarks/>
        BDI,
        
        /// <remarks/>
        BEL,
        
        /// <remarks/>
        BEN,
        
        /// <remarks/>
        BFA,
        
        /// <remarks/>
        BGD,
        
        /// <remarks/>
        BGR,
        
        /// <remarks/>
        BHR,
        
        /// <remarks/>
        BHS,
        
        /// <remarks/>
        BIH,
        
        /// <remarks/>
        BLR,
        
        /// <remarks/>
        BLZ,
        
        /// <remarks/>
        BMU,
        
        /// <remarks/>
        BOL,
        
        /// <remarks/>
        BRA,
        
        /// <remarks/>
        BRB,
        
        /// <remarks/>
        BRN,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BWA,
        
        /// <remarks/>
        CAF,
        
        /// <remarks/>
        CAN,
        
        /// <remarks/>
        CCK,
        
        /// <remarks/>
        CHE,
        
        /// <remarks/>
        CHL,
        
        /// <remarks/>
        CHN,
        
        /// <remarks/>
        CIV,
        
        /// <remarks/>
        CMR,
        
        /// <remarks/>
        COD,
        
        /// <remarks/>
        COG,
        
        /// <remarks/>
        COK,
        
        /// <remarks/>
        COL,
        
        /// <remarks/>
        COM,
        
        /// <remarks/>
        CPV,
        
        /// <remarks/>
        CRI,
        
        /// <remarks/>
        CUB,
        
        /// <remarks/>
        CXR,
        
        /// <remarks/>
        CYM,
        
        /// <remarks/>
        CYP,
        
        /// <remarks/>
        CZE,
        
        /// <remarks/>
        DEU,
        
        /// <remarks/>
        DJI,
        
        /// <remarks/>
        DMA,
        
        /// <remarks/>
        DNK,
        
        /// <remarks/>
        DOM,
        
        /// <remarks/>
        DZA,
        
        /// <remarks/>
        ECU,
        
        /// <remarks/>
        EGY,
        
        /// <remarks/>
        ERI,
        
        /// <remarks/>
        ESH,
        
        /// <remarks/>
        ESP,
        
        /// <remarks/>
        EST,
        
        /// <remarks/>
        ETH,
        
        /// <remarks/>
        FIN,
        
        /// <remarks/>
        FJI,
        
        /// <remarks/>
        FLK,
        
        /// <remarks/>
        FRA,
        
        /// <remarks/>
        FRO,
        
        /// <remarks/>
        FSM,
        
        /// <remarks/>
        GAB,
        
        /// <remarks/>
        GBR,
        
        /// <remarks/>
        GEO,
        
        /// <remarks/>
        GHA,
        
        /// <remarks/>
        GIB,
        
        /// <remarks/>
        GIN,
        
        /// <remarks/>
        GLP,
        
        /// <remarks/>
        GMB,
        
        /// <remarks/>
        GNB,
        
        /// <remarks/>
        GNQ,
        
        /// <remarks/>
        GRC,
        
        /// <remarks/>
        GRD,
        
        /// <remarks/>
        GRL,
        
        /// <remarks/>
        GTM,
        
        /// <remarks/>
        GUF,
        
        /// <remarks/>
        GUM,
        
        /// <remarks/>
        GUY,
        
        /// <remarks/>
        HKG,
        
        /// <remarks/>
        HMD,
        
        /// <remarks/>
        HND,
        
        /// <remarks/>
        HRV,
        
        /// <remarks/>
        HTI,
        
        /// <remarks/>
        HUN,
        
        /// <remarks/>
        IDN,
        
        /// <remarks/>
        IMN,
        
        /// <remarks/>
        IND,
        
        /// <remarks/>
        IRL,
        
        /// <remarks/>
        IRN,
        
        /// <remarks/>
        IRQ,
        
        /// <remarks/>
        ISL,
        
        /// <remarks/>
        ISR,
        
        /// <remarks/>
        ITA,
        
        /// <remarks/>
        JAM,
        
        /// <remarks/>
        JOR,
        
        /// <remarks/>
        JPN,
        
        /// <remarks/>
        KAZ,
        
        /// <remarks/>
        KEN,
        
        /// <remarks/>
        KGZ,
        
        /// <remarks/>
        KHM,
        
        /// <remarks/>
        KIR,
        
        /// <remarks/>
        KNA,
        
        /// <remarks/>
        KOR,
        
        /// <remarks/>
        KWT,
        
        /// <remarks/>
        LAO,
        
        /// <remarks/>
        LBN,
        
        /// <remarks/>
        LBR,
        
        /// <remarks/>
        LBY,
        
        /// <remarks/>
        LCA,
        
        /// <remarks/>
        LIE,
        
        /// <remarks/>
        LKA,
        
        /// <remarks/>
        LSO,
        
        /// <remarks/>
        LTU,
        
        /// <remarks/>
        LUX,
        
        /// <remarks/>
        LVA,
        
        /// <remarks/>
        MAC,
        
        /// <remarks/>
        MAR,
        
        /// <remarks/>
        MCO,
        
        /// <remarks/>
        MDA,
        
        /// <remarks/>
        MDG,
        
        /// <remarks/>
        MDV,
        
        /// <remarks/>
        MEX,
        
        /// <remarks/>
        MHL,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MLI,
        
        /// <remarks/>
        MLT,
        
        /// <remarks/>
        MMR,
        
        /// <remarks/>
        MNE,
        
        /// <remarks/>
        MNG,
        
        /// <remarks/>
        MNP,
        
        /// <remarks/>
        MOZ,
        
        /// <remarks/>
        MRT,
        
        /// <remarks/>
        MSR,
        
        /// <remarks/>
        MTQ,
        
        /// <remarks/>
        MUS,
        
        /// <remarks/>
        MWI,
        
        /// <remarks/>
        MYS,
        
        /// <remarks/>
        MYT,
        
        /// <remarks/>
        NAM,
        
        /// <remarks/>
        NCL,
        
        /// <remarks/>
        NER,
        
        /// <remarks/>
        NFK,
        
        /// <remarks/>
        NGA,
        
        /// <remarks/>
        NIC,
        
        /// <remarks/>
        NIU,
        
        /// <remarks/>
        NLD,
        
        /// <remarks/>
        NOR,
        
        /// <remarks/>
        NPL,
        
        /// <remarks/>
        NRU,
        
        /// <remarks/>
        NZL,
        
        /// <remarks/>
        OMN,
        
        /// <remarks/>
        PAK,
        
        /// <remarks/>
        PAN,
        
        /// <remarks/>
        PCN,
        
        /// <remarks/>
        PER,
        
        /// <remarks/>
        PHL,
        
        /// <remarks/>
        PLW,
        
        /// <remarks/>
        PNG,
        
        /// <remarks/>
        POL,
        
        /// <remarks/>
        PRI,
        
        /// <remarks/>
        PRK,
        
        /// <remarks/>
        PRT,
        
        /// <remarks/>
        PRY,
        
        /// <remarks/>
        PYF,
        
        /// <remarks/>
        QAT,
        
        /// <remarks/>
        REU,
        
        /// <remarks/>
        ROU,
        
        /// <remarks/>
        RUS,
        
        /// <remarks/>
        RWA,
        
        /// <remarks/>
        SAU,
        
        /// <remarks/>
        SDN,
        
        /// <remarks/>
        SEN,
        
        /// <remarks/>
        SGP,
        
        /// <remarks/>
        SHN,
        
        /// <remarks/>
        SJM,
        
        /// <remarks/>
        SLB,
        
        /// <remarks/>
        SLE,
        
        /// <remarks/>
        SLV,
        
        /// <remarks/>
        SMR,
        
        /// <remarks/>
        SOM,
        
        /// <remarks/>
        SPM,
        
        /// <remarks/>
        SRB,
        
        /// <remarks/>
        STP,
        
        /// <remarks/>
        SUR,
        
        /// <remarks/>
        SVK,
        
        /// <remarks/>
        SVN,
        
        /// <remarks/>
        SWE,
        
        /// <remarks/>
        SWZ,
        
        /// <remarks/>
        SYC,
        
        /// <remarks/>
        SYR,
        
        /// <remarks/>
        TCA,
        
        /// <remarks/>
        TCD,
        
        /// <remarks/>
        TGO,
        
        /// <remarks/>
        THA,
        
        /// <remarks/>
        TJK,
        
        /// <remarks/>
        TKL,
        
        /// <remarks/>
        TKM,
        
        /// <remarks/>
        TMP,
        
        /// <remarks/>
        TON,
        
        /// <remarks/>
        TTO,
        
        /// <remarks/>
        TUN,
        
        /// <remarks/>
        TUR,
        
        /// <remarks/>
        TUV,
        
        /// <remarks/>
        TWN,
        
        /// <remarks/>
        TZA,
        
        /// <remarks/>
        UGA,
        
        /// <remarks/>
        UKR,
        
        /// <remarks/>
        URY,
        
        /// <remarks/>
        USA,
        
        /// <remarks/>
        UZB,
        
        /// <remarks/>
        VAT,
        
        /// <remarks/>
        VCT,
        
        /// <remarks/>
        VEN,
        
        /// <remarks/>
        VGB,
        
        /// <remarks/>
        VIR,
        
        /// <remarks/>
        VNM,
        
        /// <remarks/>
        VUT,
        
        /// <remarks/>
        WLF,
        
        /// <remarks/>
        WSM,
        
        /// <remarks/>
        YEM,
        
        /// <remarks/>
        ZAF,
        
        /// <remarks/>
        ZMB,
        
        /// <remarks/>
        ZWE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class GeoHierarchyStatistic {
        
        private RealEstateType realEstateTypeField;
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RealEstateType realEstateType {
            get {
                return this.realEstateTypeField;
            }
            set {
                this.realEstateTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public enum RealEstateType {
        
        /// <remarks/>
        APARTMENT_RENT,
        
        /// <remarks/>
        APARTMENT_BUY,
        
        /// <remarks/>
        HOUSE_RENT,
        
        /// <remarks/>
        HOUSE_BUY,
        
        /// <remarks/>
        GARAGE_RENT,
        
        /// <remarks/>
        GARAGE_BUY,
        
        /// <remarks/>
        LIVING_RENT_SITE,
        
        /// <remarks/>
        LIVING_BUY_SITE,
        
        /// <remarks/>
        TRADE_SITE,
        
        /// <remarks/>
        HOUSE_TYPE,
        
        /// <remarks/>
        FLAT_SHARE_ROOM,
        
        /// <remarks/>
        SENIOR_CARE,
        
        /// <remarks/>
        ASSISTED_LIVING,
        
        /// <remarks/>
        OFFICE,
        
        /// <remarks/>
        INDUSTRY,
        
        /// <remarks/>
        STORE,
        
        /// <remarks/>
        GASTRONOMY,
        
        /// <remarks/>
        SPECIAL_PURPOSE,
        
        /// <remarks/>
        INVESTMENT,
        
        /// <remarks/>
        COMPULSORY_AUCTION,
        
        /// <remarks/>
        SHORT_TERM_ACCOMMODATION,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Neighbourhood))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Quarter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(City))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Region))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Country))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Continent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class GeoHierarchyElement {
        
        private string nameField;
        
        private long geoCodeIdField;
        
        private string fullGeoCodeIdField;
        
        private GeoHierarchyStatistic[] statisticsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long geoCodeId {
            get {
                return this.geoCodeIdField;
            }
            set {
                this.geoCodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fullGeoCodeId {
            get {
                return this.fullGeoCodeIdField;
            }
            set {
                this.fullGeoCodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GeoHierarchyStatistic[] statistics {
            get {
                return this.statisticsField;
            }
            set {
                this.statisticsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Neighbourhood : GeoHierarchyElement {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Quarter : GeoHierarchyElement {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class City : GeoHierarchyElement {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Region : GeoHierarchyElement {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Country : GeoHierarchyElement {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Continent : GeoHierarchyElement {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class GeoHierarchy {
        
        private Continent continentField;
        
        private Country countryField;
        
        private Region regionField;
        
        private City cityField;
        
        private Quarter quarterField;
        
        private Neighbourhood neighbourhoodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Continent continent {
            get {
                return this.continentField;
            }
            set {
                this.continentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Country country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Region region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quarter quarter {
            get {
                return this.quarterField;
            }
            set {
                this.quarterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Neighbourhood neighbourhood {
            get {
                return this.neighbourhoodField;
            }
            set {
                this.neighbourhoodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Wgs84Coordinate {
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Wgs84Address : Address {
        
        private string quarterField;
        
        private Wgs84Coordinate wgs84CoordinateField;
        
        private bool preciseHouseNumberField;
        
        private bool preciseHouseNumberFieldSpecified;
        
        private GeoHierarchy geoHierarchyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string quarter {
            get {
                return this.quarterField;
            }
            set {
                this.quarterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wgs84Coordinate wgs84Coordinate {
            get {
                return this.wgs84CoordinateField;
            }
            set {
                this.wgs84CoordinateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool preciseHouseNumber {
            get {
                return this.preciseHouseNumberField;
            }
            set {
                this.preciseHouseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool preciseHouseNumberSpecified {
            get {
                return this.preciseHouseNumberFieldSpecified;
            }
            set {
                this.preciseHouseNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeoHierarchy geoHierarchy {
            get {
                return this.geoHierarchyField;
            }
            set {
                this.geoHierarchyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class MasterDataContactDetailsType : BaseContactDetails {
        
        private bool postOfficeBoxField;
        
        private bool postOfficeBoxFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool postOfficeBox {
            get {
                return this.postOfficeBoxField;
            }
            set {
                this.postOfficeBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postOfficeBoxSpecified {
            get {
                return this.postOfficeBoxFieldSpecified;
            }
            set {
                this.postOfficeBoxFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class ExposeContactDetails : ContactDetails {
        
        private string realtorLogoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string realtorLogo {
            get {
                return this.realtorLogoField;
            }
            set {
                this.realtorLogoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("realtorContactDetail", Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class RealtorContactDetails : ContactDetails {
        
        private bool defaultContactField;
        
        private bool localPartnerContactField;
        
        private bool businessCardContactField;
        
        private long realEstateReferenceCountField;
        
        private bool realEstateReferenceCountFieldSpecified;
        
        private string externalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool defaultContact {
            get {
                return this.defaultContactField;
            }
            set {
                this.defaultContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool localPartnerContact {
            get {
                return this.localPartnerContactField;
            }
            set {
                this.localPartnerContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool businessCardContact {
            get {
                return this.businessCardContactField;
            }
            set {
                this.businessCardContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long realEstateReferenceCount {
            get {
                return this.realEstateReferenceCountField;
            }
            set {
                this.realEstateReferenceCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool realEstateReferenceCountSpecified {
            get {
                return this.realEstateReferenceCountFieldSpecified;
            }
            set {
                this.realEstateReferenceCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class messages {
        
        private Message[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Message[] message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Message {
        
        private MessageCode messageCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageCode messageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public enum MessageCode {
        
        /// <remarks/>
        MESSAGE_RESOURCE_CREATED,
        
        /// <remarks/>
        MESSAGE_RESOURCE_UPDATED,
        
        /// <remarks/>
        MESSAGE_RESOURCE_DELETED,
        
        /// <remarks/>
        MESSAGE_OPERATION_SUCCESSFUL,
        
        /// <remarks/>
        ERROR_COMMON_HEADER_PARAMETER_VALIDATION_FAILED,
        
        /// <remarks/>
        ERROR_COMMON_RESOURCE_REQUIRED,
        
        /// <remarks/>
        ERROR_COMMON_REQUEST_CONFLICT,
        
        /// <remarks/>
        ERROR_COMMON_AUTHENTICATION_REQUIRED,
        
        /// <remarks/>
        ERROR_COMMON_AUTHENTICATION_OAUTH_NONCE_EXPIRED,
        
        /// <remarks/>
        ERROR_COMMON_ACCESS_DENIED,
        
        /// <remarks/>
        ERROR_COMMON_SCHEMA_VALIDATION_FAILED,
        
        /// <remarks/>
        ERROR_COMMON_URL_PARAMETER_REQUIRED,
        
        /// <remarks/>
        ERROR_COMMON_URL_PARAMETER_VALIDATION_FAILED,
        
        /// <remarks/>
        ERROR_COMMON_URL_MULTIPLE_PARAMETERS_NOT_ALLOWED,
        
        /// <remarks/>
        ERROR_COMMON_URL_PARAMETER_NOT_SUPPORTED,
        
        /// <remarks/>
        ERROR_COMMON_NOT_IMPLEMENTED,
        
        /// <remarks/>
        ERROR_COMMON_SERVICE_UNAVAILABLE,
        
        /// <remarks/>
        ERROR_COMMON_INTERNAL_SERVER_ERROR,
        
        /// <remarks/>
        ERROR_COMMON_RESOURCE_NOT_FOUND,
        
        /// <remarks/>
        ERROR_COMMON_METHOD_NOT_ALLOWED,
        
        /// <remarks/>
        ERROR_COMMON_ACCEPT_TYPE_NOT_APPLICABLE,
        
        /// <remarks/>
        ERROR_COMMON_MEDIA_TYPE_UNSUPPORTED,
        
        /// <remarks/>
        ERROR_COMMON_BAD_REQUEST,
        
        /// <remarks/>
        ERROR_RESOURCE_NOT_SUPPORTED,
        
        /// <remarks/>
        ERROR_RESOURCE_NOT_FOUND,
        
        /// <remarks/>
        ERROR_RESOURCE_NOT_FOUND_FOR_MULTIPLE_PARAMETERS,
        
        /// <remarks/>
        ERROR_RESOURCE_VALIDATION,
        
        /// <remarks/>
        ERROR_REQUESTED_DATA_NOT_FOUND,
        
        /// <remarks/>
        ERROR_RESOURCE_NOT_UNIQUE,
        
        /// <remarks/>
        ERROR_DB_NOT_AVAILABLE,
        
        /// <remarks/>
        ERROR_CONTACT_DETAILS_MISSING,
        
        /// <remarks/>
        ERROR_INVALID_COORDINATES,
        
        /// <remarks/>
        ERROR_GEOCODING_FAILED,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Link))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StreamingVideo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedAttachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VideoFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PDFDocument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Picture))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("attachment", Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public abstract partial class Attachment {
        
        private string titleField;
        
        private string checkSumField;
        
        private string hrefField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string labelField;
        
        private System.DateTime modificationField;
        
        private bool modificationFieldSpecified;
        
        private System.DateTime creationField;
        
        private bool creationFieldSpecified;
        
        private System.DateTime publishDateField;
        
        private bool publishDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string checkSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime modification {
            get {
                return this.modificationField;
            }
            set {
                this.modificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modificationSpecified {
            get {
                return this.modificationFieldSpecified;
            }
            set {
                this.modificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                this.creationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationSpecified {
            get {
                return this.creationFieldSpecified;
            }
            set {
                this.creationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime publishDate {
            get {
                return this.publishDateField;
            }
            set {
                this.publishDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publishDateSpecified {
            get {
                return this.publishDateFieldSpecified;
            }
            set {
                this.publishDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Link : Attachment {
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class StreamingVideo : Attachment {
        
        private string videoIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string videoId {
            get {
                return this.videoIdField;
            }
            set {
                this.videoIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VideoFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PDFDocument))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public abstract partial class ExtendedAttachment : Attachment {
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class VideoFile : ExtendedAttachment {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class PDFDocument : ExtendedAttachment {
        
        private bool floorplanField;
        
        public PDFDocument() {
            this.floorplanField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool floorplan {
            get {
                return this.floorplanField;
            }
            set {
                this.floorplanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Picture : Attachment {
        
        private bool floorplanField;
        
        private bool titlePictureField;
        
        private PictureUrl[] urlsField;
        
        public Picture() {
            this.floorplanField = false;
            this.titlePictureField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool floorplan {
            get {
                return this.floorplanField;
            }
            set {
                this.floorplanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool titlePicture {
            get {
                return this.titlePictureField;
            }
            set {
                this.titlePictureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("url", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PictureUrl[] urls {
            get {
                return this.urlsField;
            }
            set {
                this.urlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class PictureUrl {
        
        private PictureScaleType scaleField;
        
        private bool scaleFieldSpecified;
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PictureScaleType scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scaleSpecified {
            get {
                return this.scaleFieldSpecified;
            }
            set {
                this.scaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public enum PictureScaleType {
        
        /// <remarks/>
        SCALE_60x40,
        
        /// <remarks/>
        SCALE_60x60,
        
        /// <remarks/>
        SCALE_73x73,
        
        /// <remarks/>
        SCALE_118x118,
        
        /// <remarks/>
        SCALE_155x40,
        
        /// <remarks/>
        SCALE_200x200,
        
        /// <remarks/>
        SCALE_210x210,
        
        /// <remarks/>
        SCALE_300x300,
        
        /// <remarks/>
        SCALE_400x300,
        
        /// <remarks/>
        SCALE_540x540,
        
        /// <remarks/>
        SCALE_1000x1000,
        
        /// <remarks/>
        SCALE_AND_CROP,
        
        /// <remarks/>
        SCALE,
        
        /// <remarks/>
        WHITE_FILLING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class realtorContactDetailsList {
        
        private RealtorContactDetails[] realtorContactDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("realtorContactDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealtorContactDetails[] realtorContactDetails {
            get {
                return this.realtorContactDetailsField;
            }
            set {
                this.realtorContactDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("realtorLogo", Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class RealtorLogo {
        
        private string realtorLogoUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string realtorLogoUrl {
            get {
                return this.realtorLogoUrlField;
            }
            set {
                this.realtorLogoUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("autopilotSettings", Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class AutopilotSettings {
        
        private bool autopilotEnabledField;
        
        private bool autopilotEnabledFieldSpecified;
        
        private bool sendEmailWithAutopilotReportField;
        
        private bool sendEmailWithAutopilotReportFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool autopilotEnabled {
            get {
                return this.autopilotEnabledField;
            }
            set {
                this.autopilotEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autopilotEnabledSpecified {
            get {
                return this.autopilotEnabledFieldSpecified;
            }
            set {
                this.autopilotEnabledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool sendEmailWithAutopilotReport {
            get {
                return this.sendEmailWithAutopilotReportField;
            }
            set {
                this.sendEmailWithAutopilotReportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendEmailWithAutopilotReportSpecified {
            get {
                return this.sendEmailWithAutopilotReportFieldSpecified;
            }
            set {
                this.sendEmailWithAutopilotReportFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("attachments", Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class Attachments {
        
        private Attachment[] attachmentField;
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Attachment[] attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class strictList {
        
        private Paging pagingField;
        
        private MatchCount[] matchCountListField;
        
        private StrictEntry[] strictEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Paging paging {
            get {
                return this.pagingField;
            }
            set {
                this.pagingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("matchCount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MatchCount[] matchCountList {
            get {
                return this.matchCountListField;
            }
            set {
                this.matchCountListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("strictEntry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StrictEntry[] strictEntry {
            get {
                return this.strictEntryField;
            }
            set {
                this.strictEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class Paging {
        
        private ReferenceLink nextField;
        
        private ReferenceLink previousField;
        
        private int pageNumberField;
        
        private bool pageNumberFieldSpecified;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int numberOfPagesField;
        
        private bool numberOfPagesFieldSpecified;
        
        private int numberOfHitsField;
        
        public Paging() {
            this.numberOfHitsField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenceLink next {
            get {
                return this.nextField;
            }
            set {
                this.nextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReferenceLink previous {
            get {
                return this.previousField;
            }
            set {
                this.previousField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified {
            get {
                return this.pageNumberFieldSpecified;
            }
            set {
                this.pageNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numberOfPages {
            get {
                return this.numberOfPagesField;
            }
            set {
                this.numberOfPagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberOfPagesSpecified {
            get {
                return this.numberOfPagesFieldSpecified;
            }
            set {
                this.numberOfPagesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numberOfHits {
            get {
                return this.numberOfHitsField;
            }
            set {
                this.numberOfHitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class ReferenceLink {
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class MatchCount {
        
        private string nameField;
        
        private string valueField;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class StrictEntry {
        
        private Wgs84Coordinate wgs84CoordinateField;
        
        private bool preciseHouseNumberField;
        
        private bool preciseHouseNumberFieldSpecified;
        
        private bool publishedAfterRequestedDateField;
        
        private bool publishedAfterRequestedDateFieldSpecified;
        
        private string hrefField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string labelField;
        
        private System.DateTime modificationField;
        
        private bool modificationFieldSpecified;
        
        private System.DateTime creationField;
        
        private bool creationFieldSpecified;
        
        private System.DateTime publishDateField;
        
        private bool publishDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Wgs84Coordinate wgs84Coordinate {
            get {
                return this.wgs84CoordinateField;
            }
            set {
                this.wgs84CoordinateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool preciseHouseNumber {
            get {
                return this.preciseHouseNumberField;
            }
            set {
                this.preciseHouseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool preciseHouseNumberSpecified {
            get {
                return this.preciseHouseNumberFieldSpecified;
            }
            set {
                this.preciseHouseNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool publishedAfterRequestedDate {
            get {
                return this.publishedAfterRequestedDateField;
            }
            set {
                this.publishedAfterRequestedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publishedAfterRequestedDateSpecified {
            get {
                return this.publishedAfterRequestedDateFieldSpecified;
            }
            set {
                this.publishedAfterRequestedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime modification {
            get {
                return this.modificationField;
            }
            set {
                this.modificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modificationSpecified {
            get {
                return this.modificationFieldSpecified;
            }
            set {
                this.modificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                this.creationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationSpecified {
            get {
                return this.creationFieldSpecified;
            }
            set {
                this.creationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime publishDate {
            get {
                return this.publishDateField;
            }
            set {
                this.publishDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publishDateSpecified {
            get {
                return this.publishDateFieldSpecified;
            }
            set {
                this.publishDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("publishObject", Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class PublishObject {
        
        private PublishObjectRealEstate realEstateField;
        
        private PublishChannel publishChannelField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PublishObjectRealEstate realEstate {
            get {
                return this.realEstateField;
            }
            set {
                this.realEstateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PublishChannel publishChannel {
            get {
                return this.publishChannelField;
            }
            set {
                this.publishChannelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class PublishObjectRealEstate {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    public partial class PublishChannel {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class publishChannels {
        
        private PublishChannel[] publishChannelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publishChannel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PublishChannel[] publishChannel {
            get {
                return this.publishChannelField;
            }
            set {
                this.publishChannelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class publishObjects {
        
        private PublishObject[] publishObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publishObject", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PublishObject[] publishObject {
            get {
                return this.publishObjectField;
            }
            set {
                this.publishObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rest.immobilienscout24.de/schema/common/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rest.immobilienscout24.de/schema/common/1.0", IsNullable=false)]
    public partial class geoHierarchyElementsStatistic {
        
        private GeoHierarchyElement parentField;
        
        private GeoHierarchyElement[] childrenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GeoHierarchyElement parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("geoHierarchyElement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GeoHierarchyElement[] children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
    }
}
